version: "3"

services:
  poll-api:
    build: "./poll-api"
    ports:
      - "1080:1080"
    environment:
      REDIS_URL: "redis:6379"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    # environment:
    #   REDIS_ARGS: "--appendonly yes"
    volumes:
      - ./redis_data/:/data
